### PR TITLE
Fix repaints causing ThrowInfiniteSeparators. 

### PR DESCRIPTION
**Pull request by mvphelps**
Also include axis name in exception if available.

This is in response to issue #1495. Avalonia apps can cause repaints, even on charts not visible in the UI. Since Invalidate() is bypassed in this case, _stepCount would increment and eventually throw. This PR removes _stepCount and makes the check for the number of separators within EnumerateSeparators, and still throws the same exception if exceeded.

Additionally to help users troubleshoot, if the Axis has a name, the exception now includes the name in the message. I can remove this if desired, in the event of users checking the contents of the message, this could represent an API change effectively.

### CODE REVIEW

**Comment by mvphelps** [comment]
For resolving NETSDK1202: https://learn.microsoft.com/en-us/dotnet/core/tools/sdk-errors/netsdk1202
Seems we need to add that. Given I'm not the maintainer, would like your input on this. But totally willing to add it, not a big deal. 

Not sure what do do about NETSDK1147. Does the build just fail to install workloads sometimes?

**Comment by beto-rodriguez** [comment]
Thanks for the PR, I will check this.

> Not sure what do do about NETSDK1147. Does the build just fail to install workloads sometimes?

Probably the environment where Github actions are running was updated, I also need to check that.

**Comment by mvphelps** [comment]
@beto-rodriguez Is see LiveChartsCore is using the various workloads for the Target framework property. I've moved the workload installation up in the build-windows.ps1 script to prior to any compilation, since all projects had failed.

**Review by beto-rodriguez — APPROVED** [review]

**Comment by beto-rodriguez** [comment]
This fix is definitively necessary and fixes the issue.

About the CI task, there are some projects that require a specific version of visual studio (WinUI and Uno at least), since I do not have control over which version is installed in the Github actions environment, I skipped those builds for now.

I will merge as soon the test pass.

**Comment by beto-rodriguez** [comment]
Tests passed, Views are compiling... probably Maui also requires a min visual studio version, I will check that and fix it in another PR.

**Comment by mvphelps** [comment]
That's great @beto-rodriguez thank you.  I will definitely contribute to your project again if I find need in the future. You are easy to collaborate with!

**Pull request merged**
