### PR TITLE
Upgrade to Avalonia 11.0.0-preview5

### PR DESCRIPTION
**Pull request by jp2masa**
Also deleted a lot of garbage in csproj files.

### CODE REVIEW

**Comment by laolarou726** [comment]
Any plans to merge this into the current branch?

**Comment by beto-rodriguez** [comment]
Thanks for the PR!

It is merged now to the Avalonia Preview branch, will merge to master when Avalonia 11 is GA.

**Review by beto-rodriguez — APPROVED** [review]

**Comment by KindOfGod** [comment]
@beto-rodriguez When will the change appear in the preview nuget package?

**Comment by kikipoulet** [comment]
> @beto-rodriguez When will the change appear in the preview nuget package? The GitHub Action failed: https://github.com/beto-rodriguez/LiveCharts2/actions/runs/4145437926

@beto-rodriguez 
Any news about this ? getting the preview nuget package would be great, many are waiting for this I think

**Comment by beto-rodriguez** [comment]
It is published now!

**Comment by kikipoulet** [comment]
> It is published now!

Thank you very much !

Didn't want to seem rude by the way, just appreciate your work.

**Pull request merged**
