### PR TITLE
Upgrade to Avalonia 11.0.0-preview7

### PR DESCRIPTION
**Pull request by jp2masa**

### CODE REVIEW

**Comment by Mrxx99** [comment]
Preview7 is out now

**Comment by batzen** [comment]
@beto-rodriguez Is there anything we can do to get this merged?

**Review by beto-rodriguez — APPROVED** [review]

**Comment by beto-rodriguez** [comment]
@batzen  Merged now, will publish this soon!

**Comment by batzen** [comment]
Thanks a lot!

**Comment by jp2masa** [comment]
> For me only Avalonia 11.0.0-preview6 is stable (preview 5 and 7 is bugged).

Did you try preview 8? Also, did you report those bugs in the Avalonia repo?

**Comment by luki5417** [comment]
> Did you try preview 8? Also, did you report those bugs in the Avalonia repo?

These bugs have already been reported and seem to have been fixed in preview 8 (I tested little).
But appeared a new problem in this issue [#11319](https://github.com/AvaloniaUI/Avalonia/issues/11319). 
The error have solution, so is ok but I don't know what other surprises await me.

If livecharts can be put up to preview 6 and it's not a problem, I'd be grateful.

If not, then I have to wait for livecharts preview 8, because now I get the error:
_'Render' in type 'CustomDrawOp' from assembly 'LiveChartsCore.SkiaSharpView.Avalonia' does not have an implementation._

I know this is not the place to write such things, but I would like to point out that something like this is happening.

Regards

**Comment by jp2masa** [comment]
> If livecharts can be put up to preview 6 and it's not a problem, I'd be grateful.

In general I don't think it's a good idea to pin a dependency to a preview version. I opened #1011 to upgrade to preview 8, hope it gets merged soon. It would be very helpful if you could test preview 8 and report any issues you find. I don't think there will be many more breaking changes for Avalonia 11.0, it's mostly bug fixes now.

**Comment by beto-rodriguez** [comment]
Merged and publish, feel free to try the latest version @luki5417

**Pull request merged**
